version: 0.2
phases:
  install:
    commands:
      - echo "install step"
  pre_build:
    commands:
      - echo "pre_build step"
  build:
    commands:
      - aws s3 sync --delete . "s3://www.osaagyefo.com"
  post_build:
    commands:
      - echo "post_build step"
      - aws cloudfront create-invalidation --distribution-id E1J4L7ICX9Y5J8 --paths '/*'
